# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
    pull_request:
permissions:
    contents: read
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v4.1.4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v4.0.0
            - name: Set up Node.js
              uses: actions/setup-node@v4.0.2
            - name: Run Cake
              run: |
                  ./cake
            - name: Upload artifacts
              if: always()
              uses: actions/upload-artifact@v4.3.3
              with:
                  name: ${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}
                  path: |
                      out/bin
                      out/log
